run:
  timeout: 10m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - revive
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - errcheck
    - gosec
    - gocyclo
    - dupl
    - misspell
    - goconst
    - gocritic
    - prealloc
    - nilerr
    - whitespace

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment  # Disable fieldalignment checks (already optimized manually)

  gocyclo:
    min-complexity: 60  # Main menu and config interaction are complex by design

  prealloc:
    # Only report if preallocation can save >10 allocations
    simple: true
    range-loops: true
    for-loops: false

  dupl:
    threshold: 100

  goconst:
    min-len: 2
    min-occurrences: 3

  misspell:
    locale: US

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst
        - prealloc
        - gocritic

    - path: listener/
      text: "G101"  # Ignore potential credentials hardcoded in listener tests

    # Ignore fmt.Scanln/Scanf errors in main.go (user input scenarios)
    - path: cmd/serial-server/main.go
      linters:
        - errcheck
      text: "Error return value of.*fmt.Scan(ln|f)"

    # Ignore fmt.Sscanf errors in frp.go (user input scenarios)
    - path: frp/frp.go
      linters:
        - errcheck
      text: "Error return value of.*fmt.Sscanf"

    # Ignore connection write errors (best-effort logging)
    - path: listener/listener.go
      linters:
        - errcheck
      text: "Error return value of.*conn.Write"

    # Ignore SetReadDeadline errors (non-critical)
    - path: listener/listener.go
      linters:
        - errcheck
      text: "Error return value of.*conn.SetReadDeadline"

    # Ignore ifElseChain in main.go and frp.go (complex menu logic)
    - path: cmd/serial-server/main.go
      linters:
        - gocritic
      text: "ifElseChain"

    - path: frp/frp.go
      linters:
        - gocritic
      text: "ifElseChain"

    # Ignore prealloc in wizard and main (dynamic list sizes)
    - path: wizard/wizard.go
      linters:
        - prealloc

    - path: cmd/serial-server/main.go
      linters:
        - prealloc

    - path: frp/frp.go
      linters:
        - prealloc

    # Ignore unusedwrite in tests (intentional test data)
    - path: _test\.go
      linters:
        - govet
      text: "unusedwrite"

    # Ignore SA1019 (deprecated Temporary) - acceptable for this use case
    - path: listener/listener.go
      linters:
        - staticcheck
      text: "SA1019"

    # Ignore ineffassign in main.go (intentional state flag)
    - path: cmd/serial-server/main.go
      linters:
        - ineffassign

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
