run:
  timeout: 10m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - revive
    - staticcheck
    - ineffassign
    - unused
    - errcheck
    - gosec
    - gocyclo
    - dupl
    - misspell
    - goconst
    - gocritic
    - prealloc
    - nilerr
    - whitespace

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment  # Disable fieldalignment checks (already optimized manually)

  gocyclo:
    min-complexity: 60  # Main menu and config interaction are complex by design

  prealloc:
    # Only report if preallocation can save >10 allocations
    simple: true
    range-loops: true
    for-loops: false

  dupl:
    threshold: 100

  goconst:
    min-len: 2
    min-occurrences: 3

  misspell:
    locale: US

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

issues:
  # No exclusions - all linters run on all code
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  print-issued-lines: true
  print-linter-name: true
